[workspace]
members = ["crates/*"]

[workspace.package]
authors = ["Ayman Al-Qadhi <alqd@protonmail.com>"]
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
readme = true

[workspace.dependencies]
